# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 7.0
  - 7.1
  - 7.2

services:
    - mysql
    - riak
    - mongodb
    - memcached
    - redis-server
    - docker

before_install:
    - pecl channel-update pecl.php.net
    - echo yes | pecl upgrade apcu
    - phpenv config-add ./tests/_travis/php.ini
    - mysql -e 'CREATE DATABASE abexto_amylian_tests;
    
env:
    global:
        - db_username=travis
        - db_password=

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - phpunit $PHPUNIT_FLAGS